apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: project-a-db
spec:
  instances: {{ .Values.cnpg.cluster.instances }}
  bootstrap:
    initdb:
      database: app
      owner: app
  postgresql:
    parameters:
      shared_buffers: "256MB"
  resources: {{ toYaml .Values.cnpg.cluster.resources | nindent 4 }}
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: {{ .Values.cnpg.cluster.major }}
  storage: {{ toYaml .Values.cnpg.cluster.storage | nindent 4 }}
