apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: project-a-db
spec:
  instances: {{ .Values.cnpg.cluster.instances }}
  postgresql: {{ toYaml .Values.cnpg.cluster.postgresql | nindent 4 }}
  resources: {{ toYaml .Values.cnpg.cluster.resources | nindent 4 }}
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: {{ .Values.cnpg.cluster.major }}
  storage: {{ toYaml .Values.cnpg.cluster.storage | nindent 4 }}
