apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: {{ .Values.cnpg.instances }}
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: {{ .Values.cnpg.major }}
  storage:
    size: {{ .Values.cnpg.storage.size }}
