namespace: acme-project-a-prod
clientSlug: acme
nameOverride: acme-project-a-prod
fullnameOverride: acme-project-a-prod
image:
  repository: golang-api
  tag: fd20be3
  pullPolicy: Never
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 60
