apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../../../helm/charts
helmCharts:
  - name: project-a
    releaseName: project-a
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: project-a
      environment: prod
      tenant: acme
