golang-api:
  enabled: true
  image:
    tag: fd20be3
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 65
    targetMemoryUtilizationPercentage: 60
  podLabels:
    environment: prod
cnpg:
  cluster:
    instances: 3
    storage:
      size: 4Gi
    postgresql:
      parameters:
        shared_buffers: "68MB"
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "400m"
        memory: "512Mi"
