golang-api:
  enabled: true
  image:
    tag: 10fd14c
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 65
    targetMemoryUtilizationPercentage: 60
  podLabels:
    environment: prod
  httpRoute:
    enabled: true
    annotations: {}
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: platform
        namespace: envoy-gateway-system
        sectionName: https
    hostnames: [acme.project-a.internal]
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /golang-api
        filters:
          - type: URLRewrite
            urlRewrite:
              path:
                type: ReplacePrefixMatch
                replacePrefixMatch: /
cnpg:
  cluster:
    instances: 3
    storage:
      size: 4Gi
    postgresql:
      parameters:
        shared_buffers: "68MB"
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "400m"
        memory: "512Mi"
