{{- if .Values.secretStore.enabled -}}
{{- $secretBasePath := required "secretBasePath is required when secretStore.enabled is true" .Values.secretStore.vault.secretBasePath -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "golang-api.fullname" . }}
  labels: {{- include "golang-api.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "golang-api.fullname" . }}-vault"
    kind: SecretStore
  refreshInterval: "1m"
  target:
    name: {{ include "golang-api.fullname" . }}
    # Specifies the ExternalSecret ownership details in the created Secret. Options:
    # - Owner: (default) Creates the Secret and sets .metadata.ownerReferences. If the ExternalSecret is deleted, the Secret will also be deleted.
    # - Merge: Does not create the Secret but merges data fields into the existing Secret (expects the Secret to already exist).
    # - Orphan: Creates the Secret but does not set .metadata.ownerReferences. If the Secret already exists, it will be updated.
    # - None: Does not create or update the Secret (reserved for future use with injector).
    creationPolicy: Owner
    # Specifies what happens to the Secret when data fields are deleted from the provider (e.g., Vault, AWS Parameter Store). Options:
    # - Retain: (default) Retains the Secret if all Secret data fields have been deleted from the provider.
    # - Delete: Removes the Secret if all Secret data fields from the provider are deleted.
    # - Merge: Removes keys from the Secret but not the Secret itself.
    deletionPolicy: Merge
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: {{ $secretBasePath }}
        property: APP_KEY
{{- end }}
