{{- if .Values.secretStore.enabled -}}
{{- $provider := required "secretStore.provider is required when secretStore.enabled is true" .Values.secretStore.provider -}}
{{- if eq $provider "vault" -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: "{{ include "golang-api.fullname" . }}-vault"
  labels: {{- include "golang-api.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"

      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ required "secretStore.vault.role is required when secretStore.enabled is true and provider is vault" .Values.secretStore.vault.role }}

          serviceAccountRef:
            name: {{ include "golang-api.serviceAccountName" . }}
            audiences:
              - vault
{{- end -}}
{{- end }}
