{{- if .Values.secretStore.enabled -}}
{{- $provider := required "secretStore.provider is required when secretStore.enabled is true" .Values.secretStore.provider -}}
{{- if eq $provider "vault" -}}
{{- $defaultVaultRole := include "golang-api.fullname" . -}}
{{- if not (contains $defaultVaultRole .Release.Namespace) -}}
  {{- $defaultVaultRole = printf "%s-%s" .Release.Namespace $defaultVaultRole -}}
{{- end -}}
{{- $vaultRole := default $defaultVaultRole .Values.secretStore.vault.role -}}
{{- $vaultPath := required "secretStore.vault.path is required when secretStore.enabled is true and provider is vault" .Values.secretStore.vault.path -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: "{{ include "golang-api.fullname" . }}-vault"
  labels: {{- include "golang-api.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: {{ $vaultPath | quote }}
      version: "v2"

      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ $vaultRole }}

          serviceAccountRef:
            name: {{ include "golang-api.serviceAccountName" . }}
            audiences:
              - vault
{{- end -}}
{{- end }}
