golang-api:
  enabled: true
  fullnameOverride: golang-api

cnpg:
  cluster:
    instances: 1
    major: 18
    storage:
      size: 1Gi
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "1Gi"
        cpu: "1"
